USE MEDIA_PLATFORM_DB;
/* 
=============================================================================
QUERY 5: Total Watch Time per User
=============================================================================
HOW IT WORKS: Aggregates the total minutes consumed by each user to identify 
the platform's heaviest streamers.
*/
SELECT user_id, SUM(minutes_watched) AS total_minutes_streamed 
FROM Watch_History 
GROUP BY user_id 
ORDER BY total_minutes_streamed DESC;

/* 
=============================================================================
QUERY 6: Content Volume by Genre
=============================================================================
HOW IT WORKS: Counts how many unique movies/shows exist under each genre category 
to understand catalog distribution.
*/
SELECT genre_id, COUNT(content_id) AS total_titles 
FROM Content 
GROUP BY genre_id;

/* 
=============================================================================
QUERY 7: Estimated Monthly Recurring Revenue (MRR)
=============================================================================
HOW IT WORKS: Multiplies the cost of a plan by the number of users on it to 
calculate the gross revenue generated by each subscription tier.
*/
SELECT p.plan_name, (COUNT(u.user_id) * p.monthly_price) AS total_tier_revenue
FROM Plans p
JOIN Users u ON p.plan_id = u.plan_id
GROUP BY p.plan_name, p.monthly_price;

/* 
=============================================================================
QUERY 8: Most Watched Content (By Total Time)
=============================================================================
HOW IT WORKS: Sums the total minutes watched across all users for each piece 
of content to see what is consuming the most server bandwidth.
*/
SELECT content_id, SUM(minutes_watched) AS global_watch_minutes 
FROM Watch_History 
GROUP BY content_id 
ORDER BY global_watch_minutes DESC;